### ISSUE TITLE
Incorrect address for Wiz

### ISSUE THREAD

**Issue by dhruvnnd** [kimlimjustin/kimlimjustin.com#5]
I was going through your beautiful website and under the **Notable Projects** section, 
I clicked on the link to Wiz but the address is incorrect, it redirects to https://github.com/kimlimjustin/xiz instead of the correct address. 
In the URL, it says `xiz` instead of `wiz`

**Comment by kimlimjustin** [comment]
Whoops, didn't realize that, thanks for your issue, pushed a fix for that!
